-- 권한 코드 테이블
CREATE TABLE Auth 
(
	AUTH_CODE INT PRIMARY KEY,
    AUTH_NAME VARCHAR(50) NOT NULL
);

-- 메뉴 정보 테이블
CREATE TABLE Menu 
(
	MENU_ID INT PRIMARY KEY,
    PARENT_ID INT NOT NULL,
    MENU_NAME VARCHAR(100) NOT NULL,
    FORM_NAME VARCHAR(100),
    MIN_AUTH_CODE INT,
    MENU_ORDER INT
);

-- 직원 정보 테이블
CREATE TABLE User
(
	USER_ID VARCHAR(50) PRIMARY KEY,
    USER_PWD VARCHAR(225) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    AUTH_CODE INT NOT NULL
);