object Form37: TForm37
  Left = 2402
  Top = 137
  Width = 1305
  Height = 879
  ActiveControl = FlatCheckBox1
  Caption = #44160#51652#44208#44284' '#51204#45804#53685#44228' [VHMGBBZ044S]'
  Color = clWhite
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = #45208#45588#44256#46357
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 15
  object FlatPanel1: TFlatPanel
    Left = 56
    Top = 176
    Width = 994
    Height = 129
    ParentColor = True
    TabOrder = 0
    UseDockManager = True
    object FlatPanel3: TFlatPanel
      Left = 1
      Top = 1
      Width = 992
      Height = 35
      ParentColor = True
      TabOrder = 0
      UseDockManager = True
      object FlatLabel7: TFlatLabel
        Left = 472
        Top = 3
        Width = 55
        Height = 25
        Alignment = taRightJustify
        TextBorder = 0
        BevelInner = beNone
        BevelOuter = beNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        Caption = #51217#49688#52376
        Color = clWhite
        ParentFont = False
        ParentColor = False
        ShowRect = False
        ShowEssential = True
      end
      object FlatLabel2: TFlatLabel
        Left = 254
        Top = 4
        Width = 65
        Height = 25
        Alignment = taRightJustify
        TextBorder = 0
        BevelInner = beNone
        BevelOuter = beNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        Caption = #54924#48156#51068#51088
        Color = clWhite
        ParentFont = False
        ParentColor = False
        ShowRect = False
        ShowEssential = True
      end
      object FlatLabel1: TFlatLabel
        Left = 675
        Top = 5
        Width = 64
        Height = 25
        Alignment = taRightJustify
        TextBorder = 0
        BevelInner = beNone
        BevelOuter = beNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        Caption = #51217#49688#44396#48516
        Color = clWhite
        ParentFont = False
        ParentColor = False
        ShowRect = False
        ShowEssential = True
      end
      object FlatLabel4: TFlatLabel
        Left = 12
        Top = 4
        Width = 64
        Height = 25
        Alignment = taRightJustify
        TextBorder = 0
        BevelInner = beNone
        BevelOuter = beNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = #45208#45588#44256#46357
        Font.Style = []
        Caption = #51089#50629#49440#53469
        Color = clWhite
        ParentFont = False
        ParentColor = False
        ShowRect = False
        ShowEssential = True
      end
      object pn_Panel013: TFlatPanel
        Left = 534
        Top = 5
        Width = 124
        Height = 23
        ParentColor = True
        TabOrder = 0
        UseDockManager = True
        object FlatCheckBox7: TFlatCheckBox
          Left = 5
          Top = 2
          Width = 14
          Height = 17
          TabOrder = 0
          TabStop = True
        end
        object FlatComboBox21: TFlatComboBox
          Left = 20
          Top = 0
          Width = 104
          Height = 23
          Color = clWindow
          ItemHeight = 15
          TabOrder = 1
          Text = '1-'#51333#47196#51333#44160
          ItemIndex = -1
        end
      end
      object FlatPanel4: TFlatPanel
        Left = 745
        Top = 6
        Width = 124
        Height = 23
        ParentColor = True
        TabOrder = 1
        UseDockManager = True
        object FlatCheckBox1: TFlatCheckBox
          Left = 5
          Top = 2
          Width = 14
          Height = 17
          TabOrder = 0
          TabStop = True
        end
        object FlatComboBox1: TFlatComboBox
          Left = 20
          Top = 0
          Width = 104
          Height = 23
          Color = clWindow
          ItemHeight = 15
          TabOrder = 1
          Text = 'A-'#51333#54633#44160#51652
          ItemIndex = -1
        end
      end
      object FlatComboBox3: TFlatComboBox
        Left = 326
        Top = 5
        Width = 107
        Height = 23
        Color = clWindow
        ItemHeight = 15
        TabOrder = 2
        ItemIndex = -1
      end
      object FlatPanel7: TFlatPanel
        Left = 83
        Top = 6
        Width = 166
        Height = 23
        ParentColor = True
        TabOrder = 3
        UseDockManager = True
        object FlatRadioButton3: TFlatRadioButton
          Left = 9
          Top = 2
          Width = 72
          Height = 17
          Caption = #54924#48156#51068#48324
          TabOrder = 0
        end
        object FlatRadioButton4: TFlatRadioButton
          Left = 81
          Top = 2
          Width = 80
          Height = 17
          Caption = #44160#51652#51068#48324
          TabOrder = 1
        end
      end
      object FlatButton1: TFlatButton
        Left = 914
        Top = 5
        Width = 72
        Height = 23
        Color = clSilver
        Caption = #51312#54924
        ParentColor = False
        TabOrder = 4
      end
    end
  end
end
